# frozen_string_literal: true

class CalendarController < ApplicationController
  skip_after_action :verify_policy_scoped # TODO: remove the funny scoping

  def index
    @initial_state = initial_state

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: initial_state }
    end
  end

  def initial_state
    {
      user: {
        user_id: current_user.id,
        signed_in: true,
        selected_view: 'Session',
        selected_template: current_training_template&.id
      },
      templates: current_user.training_templates,
      workouts: current_user.workouts.sort_by(&:day_number),
      blocks: current_user.blocks.sort_by(&:order),
      excercises: current_user.excercises,
      sessionProgressions: current_user.session_progressions,
      setsRepsSchemeList: setsRepsSchemeList,
      excerciseList: excerciseList
      # progressions: current_user.progressions
    }
  end

  def show
    training_template = current_user.training_templates.find(params[:id])

    authorize training_template

    session[:training_template_id] = training_template.id

    head :ok
  end

  private

  def setsRepsSchemeList
    [
      "3x10",
      "3x8",
      "3x10,8,6",
      "5x10,8,6,4,2"
    ]
  end

  def excerciseList
    [
      "Clean & Jerk",
      "Clean",
      "Hang Clean",
      "Power Clean",
      "Hang Power Clean",
      "Muscle Clean",
      "Clean Pull",
      "2-Position Clean",
      "2-Positions Power Clean",
      "3-Posistion Clean",
      "3-Posisiton Power Clean",
      "Block Clean Pull",
      "Block Clean",
      "Block Power Clean",
      "Clean High Pull",
      "Deficit Clean High Pull",
      "Deficit Clean Pull",
      "Clean Segment Pull",
      "Dip Clean",
      "Hang Clean Pull",
      "Hip Clean",
      "Power Clean into Front Squat",
      "Tall Muscle Clean",
      "Dumbbell Clean",
      "Dumbbell Clean and Jerk",
      "Snatch",
      "Hang Snatch",
      "Power Snatch",
      "Hang Power Snatch",
      "Clean Grip Snatch",
      "Snatch Pull",
      "Muscle Snatch",
      "2-Position Power Snatch",
      "2-Position Snatch",
      "3-Position Power Snatch",
      "3-Position Snatch",
      "Block Power Snatch",
      "Block Snatch",
      "Block Snatch Pull",
      "Dip Muscle Snatch",
      "Dip Power Snatch",
      "Dip Snatch",
      "Hang Muscle Snatch",
      "Hang Muscle Squat Snatch",
      "Hang Snatch Pull",
      "Snatch High Pull",
      "Hip Snatch",
      "Muscle Squat Snatch",
      "Power Snatch From Power Position",
      "Power Snatch into Overhead Squat",
      "Press In Snatch (Sots Press)",
      "Snatch Balance",
      "Segment Power Snatch",
      "Segment Snatch",
      "High Hang Snatch Pull",
      "Tall Muscle Snatch",
      "Dumbbell Snatch",
      "Split Jerk",
      "Power Jerk",
      "Jerk Balance",
      "Behind the Neck Push Kerk",
      "Push Jerk",
      "Jerk Drive",
      "Pause Jerk",
      "Push Jerk in Split",
      "Dumbbell Push Jerk",
      "Dumbbell Split Jerk",
      "Single Arm Dumbbell Jerk",
      "Single Arm Dumbell Push Jerk",
      "Air Squat",
      "Overhead Squat",
      "Back Squat",
      "Font Squat",
      "Goblet Squat",
      "Safety Bar Squat",
      "Zercher Squat",
      "Jump Squat",
      "Lateral Squat",
      "Box Squat",
      "Sumo Squat",
      "Wall Squat",
      "Hack Squat",
      "Dumbbell Split Squat",
      "Barbell Split Squat",
      "Single-leg Squat",
      "Pistol Squat",
      "Forward Lunge (Dumbbell)",
      "Walking Lunge (Dumbbell)",
      "Reverse Lunge (Dumbbell)",
      "Lateral Lunge (Dumbbell)",
      "Forward Lunge (Barbell)",
      "Walking Lunge (Barbell)",
      "Reverse Lunge (Barbell)",
      "Lateral Lunge (Barbell)",
      "Overhead Lunges",
      "Overhead Reverse Lunges",
      "Overhead Split Squat",
      "Overhead Lateral Lunge",
      "Overhead Walking Lunges",
      "Step-Up (Dumbbell)",
      "Step-Up (Barbell)",
      "Leg Press",
      "Single-leg Leg Press",
      "Lateral Step-Up",
      "Leg Extension",
      "Step Down",
      "Front Foot Elevated Split Squat",
      "Weighted Box Step Up ",
      "Weighted Box Step Over",
      "Goblet Bulgarian Split Squat",
      "Goblet Lateral Lunges",
      "Goblet Lateral Split Squat",
      "Goblet Split Squat",
      "Dumbbell Overhead Squat",
      "Deadlift",
      "Sumo Deadlift",
      "Deficit Deadlift",
      "Deadlift from Blocks",
      "Rack Pull",
      "Snatch Grip Deadlift",
      "Good Morning",
      "Seated Good Morning",
      "Sumo Good Morning",
      "Dumbbell Romanian Deadlift (RDL)",
      "Dumbbell Romanian Deadlift 1-Arm/1-Leg (Contralateral)",
      "Dumbbell Romanian Deadlift 1-Arm/1-Leg (Ipsilateral)",
      "Dumbell Romanian Deadlift 2-Arm/1-Leg",
      "Single-leg Romanian Deadlift (Barbell) (RDL)",
      "Romainian Deadlift (Barbell)",
      "Zerher Romanian Deadlift (RDL)",
      "Stiff-Legged Deadlift",
      "Kettlebell Swing",
      "Hamstring Curl",
      "Single-Leg Good Morning",
      "Single Leg Hip Trust",
      "Hip Thrust",
      "Weighted Glute Bridge",
      "Weight Single Leg Glute Bridge",
      "Dumbbell Deadlift",
      "Glute Bridge (Ball)",
      "Glute Bridge (Elevated Feet)",
      "Glute Bridge (Floor)",
      "Glute Bridge Single Leg (Ball)",
      "Glute Bridge Single Leg (Elevated Feet)",
      "Glute Bridge Single Leg (Floor)",
      "Glute Bridge Single Leg Alternating (Floor)",
      "Glute Ham Raise",
      "Glute Ham Raise ISO Hold",
      "Glute Ham Raise Single Leg ISO Hold",
      "Glute Ham Raise Drop Catch",
      "Glute Ham Raise Single Leg Drop Catch",
      "Hamstring Slide Boards",
      "Hamstring Slide Boards Single Leg",
      "Straight Leg Hip Bridge",
      "Single Leg Straight Leg Hip Bridge",
      "Ball Leg Curls",
      "Single Leg Ball Leg Curls",
      "Copenhagen Plank (Long Lever)",
      "Copenhagen Plank (Short Lever)",
      "Back Extension",
      "Jefferson Curl",
      "Reverse Hyper",
      "Rotation Back Extension",
      "Hyper 45 degree",
      "Hyper 45 degree Single Leg",
      "Hyper 90 degree",
      "Hyper 90 degree Single Leg",
      "Sled Push",
      "Sled Pull",
      "Farmers Walks",
      "Sled Backward Walk",
      "Sled Cross Over Walk",
      "Sled Diagonal Bakcward Pushes",
      "Sled Lateral Pushes",
      "Sled Marching",
      "Sled Walking Lunges",
      "Bench Press",
      "Incline Bech Press",
      "Decline Bench Press",
      "Close Grip Bench Press",
      "Dumbbell Bench Press",
      "Incline Dumbbel Bench Press",
      "Single Arm Incline Dumbbel Bench Press",
      "Single-Arm Dumbbel Bench Press",
      "Alternating Dumbbel Bench Press",
      "Alternating Incline Dumbbel Bench Press",
      "Pause Bench Press",
      "Dumbbell Floor Press",
      "Barbell Floor Press",
      "Push Up",
      "Incline Push Up",
      "Eccentric Push Up",
      "Barbell Overhead Press",
      "Dumbell Overhead Press",
      "Seated Dumbell Overhead Press",
      "Dumbell Push Press",
      "Single-Arm Dumbbell Push Press",
      "Snatch Press",
      "Snatch Push Press",
      "Barbell Push Press",
      "Dumbbell Push Press",
      "Single Arm Dumbbell Push Press",
      "Alternating Dumbbell Shoulder Press",
      "Sots Press",
      "Arnold Press",
      "Half-Kneeling Single Arm Dumbell Press",
      "Half-kneeling Land Mine Press",
      "Single Arm Land Mine Press",
      "Military Press",
      "Cuban Press (Barbell)",
      "Cuban Press (Dumbell)",
      "Ring Dips",
      "Dips",
      "Dumbbell Row",
      "Barbell Bent Over Row",
      "Inverted Row (Supinated)",
      "Inverted Row (Pronated)",
      "Seated Cable Row",
      "Seated Cable Row (Pronated)",
      "Seated Cable Row (Rope)",
      "Seated Cable Row (Supinated)",
      "Single Arm Seated Cable Row",
      "Ring Rows",
      "TRX Rows",
      "Pendlay Row",
      "Dumbell Banch Pull",
      "Barbell bench Pull",
      "Feet Elvevated Inverted Row",
      "Single Arm Cable Row (Pronated)",
      "Single Arm Cable Row (Supinated)",
      "Chest Suported Incline Row",
      "DB Bent Over Row 1-Arm (Neutral)",
      "DB Bent Over Row 1-Arm (Wide)",
      "DB Bent Over Row 2-Arm (Alternating)",
      "DB Bent Over Row 2-Arm (Neutral)",
      "DB Bent Over Row 2-Arm (Wide)",
      "Rings Inverted Row (Neutral)",
      "Rings Inverted Row (Rotation)",
      "Rings Inverted Row (Wide)",
      "Rings Inverted Row 1-Arm",
      "T-Bar Row",
      "Rings Pull Ups (Neutral)",
      "Rings Pull Ups (Pronated)",
      "Rings Pull Ups (Supinated)",
      "Rings Pull Ups (Wide)",
      "Rope Climbs",
      "Towel Pull-ups",
      "Chin Up (overhand)",
      "Chin Up (underhand)",
      "Chin Up (netural)",
      "Lat Pull Down (Neutral)",
      "Lat Pull Down (Pronated)",
      "Lat Pull Down (Supinated)",
      "Lat Pull Down (Wide)",
      "Close Grip lat Pulldown",
      "Barbell Upright Row",
      "Eccentric Chin Ups",
      "Barbell Curls",
      "Dumbbell Curls",
      "Alternating Dumbell Curls",
      "EZ Bar Curls",
      "Preacher Curls",
      "Cable Curls",
      "Hammer Curls",
      "Single Arm Cable Curls",
      "Tricep Push Down",
      "Overhead Tricep Extensions",
      "Skull Crushers",
      "Dumbbell Skull Crushers",
      "Rope Push Downs",
      "Single Arm Tricep Push Down",
      "Dumbell External Rotation",
      "Dumbell Internal Rotation",
      "Band External Rotation 0 Deg",
      "Band External Rotation 90 Deg",
      "Band Row to External Rotation 90 Deg",
      "Eccentric Band External Rotation 0 Deg",
      "Eccentric Band External Rotation 90 Deg",
      "Supine Eccentric External Roation 90 Deg",
      "Band High Row to Y",
      "TRX-Y's",
      "TRX-I's",
      "TRX-T's",
      "TRX-I,T,Y",
      "Cable Face Pull",
      "TRX Face Pull",
      "Band Face Pull",
      "Band Pull Apart",
      "Dumbbel Front Raise",
      "Dumbbell Lateral Raise",
      "Dumbbell Rear Delt Flys",
      "Dumbbell Flys",
      "Dumbbell Upright Row",
      "Alternating Dumbell Uprigth Row",
      "Band Overhead Y",
      "Handstand Hold",
      "Handstand Walk ",
      "Handstand Push Up ",
      "Bar Muscle Up",
      "Ring Muscle Up",
      "AB Rollout",
      "Alternating Leg Raise",
      "Leg Raises",
      "Back Plank",
      "Bird Dog",
      "Cross Body Chop",
      "Crunch",
      "Dead Bug",
      "Decline Sit-Up",
      "Drangon Fly",
      "Floor Wipers",
      "Flutter Kicks",
      "GHD Sit-Up",
      "GHD Sit-Up Hold",
      "Hanging Leg Raise",
      "Hollow Body Hold",
      "Hollow Body Rock",
      "Jack Knife",
      "TRX Jack Knife",
      "Toes to Bar",
      "L-Sit",
      "Plank",
      "Pallof Press",
      "Plank March",
      "Plank Pull-Through",
      "Reverse Crunch",
      "Rolling Pin",
      "Russian Twist",
      "Side Bend",
      "Side Plank",
      "Side Plank + Leg Lift",
      "Side Plank Lift",
      "Standing Twist",
      "Star Side Plank",
      "Super Man Hold",
      "Sky Divers",
      "V-Up",
      "Windshield Wipers",
      "Ab Mat Sit Up ",
      "Box Jumps",
      "Burpee Broad Jump",
      "Burpee Box Jump ",
      "Burpee Box Jump Over",
      "Box Jump Over",
      "Skipping",
      "Double Unders",
      "Drop Jump ",
      "Depth Jump",
      "High Hurdle Jumps",
      "Low Hurdle Hop",
      "High Hurdle Hop",
      "Power Skip",
      "Pogo Hops",
      "Tuck Jump",
      "Split Squat Jumps",
      "Speed Skaters",
      "Lateral Box Jump",
      "Trap-Bar Jump",
      "Weighted Box Jumps",
      "Eccentric Box Jumps",
      "Seated Box Jumps",
      "Broard Jump",
      "Squat Jump",
      "Bounding",
      "Medicine Ball Chest Pass",
      "Wall Balls",
      "Sandbag Over The Shoulder",
      "Chest Pass",
      "Kneeling Chest Pass",
      "Half Kneeling Chest Pass",
      "Side to Side Pass",
      "Seated Lateral Pass",
      "Seated Shot Put",
      "Wood Chop Throw",
      "Slam",
      "Split Stance Lateral Toss",
      "Lateral Power Throw",
      "Pitcher Throw",
      "Single Leg Throw In",
      "Over the Shoulder Toss",
      "Single Step Shot Put",
      "Front Facing Heave",
      "Row",
      "Run",
      "Swim",
      "Bike",
      "Assult Bike",
      "Bike Erg",
      "Ski Erg",
      "Battle Ropes"
    ]
  end
end
